#####
# Exporting LEPAS data for Zach Amidon's whitefish project
# JMH 3 Feb 2021, updated 28 Feb 21

###
# Required libraries
###
library(tidyverse)
library(RSQLite)
library(here)

####
# Get data from database
####

# location of database
# database should be kept outside of repo
# I keep right outside of my github repo, find with getwd
# put in name of db
LEPASdbPath <- file.path(here::here("/Users/hood.211/Dropbox/JMH_dropbox/stephanson2/projects/6_Research/FADX09/01_LEPASgitHub/"), 
                         "LEPAS_20210201.db")

# Connect to database -- change filepath as needed.
lpdb <- dbConnect(SQLite(), LEPASdbPath)

# Pull relevant columns from tables using embedded SQL code.
# this gets the "raw" biomass data
Zfin <- dbGetQuery(lpdb, "SELECT 
                   ZF.Sample_ID,
                   ZF.Genus_sp_lifestage,
                   ZF.Life_stage,
                   ZF.Zoop_biomass
                   FROM Zoop_final ZF")

# this gets the environmental data
Zsmp <- dbGetQuery(lpdb, "SELECT
                   ZS.Sample_ID,
                   ZS.Sample_date,
                   ZS.Sample_site,
                   ZS.Project,
                   ZS.Surface_temp
                   FROM Zoop_sample_info ZS")

# taxonomic information
Ztaxa <- dbGetQuery(lpdb,"SELECT
                    ZT.Genus_sp_lifestage,
                    ZT.Genus_sp_95toPresent,
                    ZT.Order1
                    FROM Zoop_taxa_groups ZT")


############
# PROCESS AND SUMMARIZE DATA
############

############
# 1) Get years and sites Zach wants
############
WBLEPASsites <- c('36-873', '37-890', '29-905', '27-918', '16-970', '14-972', '8-994', '3-996')

ZP1 <- Zfin %>% 
  # get sample information
  left_join(Zsmp, by = "Sample_ID") %>% 
  # get taxa information
  left_join(Ztaxa %>% 
              select(- Genus_sp_95toPresent), by = "Genus_sp_lifestage") %>% 
  mutate(Sample_date = as.POSIXct(Sample_date, format = "%Y-%m-%d"),
         Y = as.numeric(as.character(strftime(Sample_date, format = "%Y")))) %>% 
  # select dates
  filter(Y >= 1995 & Y < 2020) %>% 
  # Select sites
  filter(Sample_site %in% WBLEPASsites) %>% 
  # make all younger individuals immatures - year-to-year comparisons are not possible without this
  # Limnocalanus is the only copepod this doesn't apply too
  mutate(Genus_sp_lifestage = ifelse(Order1=="Calanoida" & Life_stage=="Younger", "Calanoida_immature", Genus_sp_lifestage),
         Genus_sp_lifestage = ifelse(Order1=="Cyclopoida" & Life_stage=="Younger", "Cyclopidae_immature", Genus_sp_lifestage)) %>% 
  # make new lifestage with younger/older combined and Egg
  mutate(Life_stage2 = as.factor(as.character(ifelse(Life_stage == "Egg", Life_stage,
                                                      ifelse(Life_stage == "Older", "YO",
                                                             ifelse(Life_stage == "Younger", "YO", Life_stage)))))) %>% 
  mutate(across(c(Sample_ID:Life_stage, Sample_site, Project), factor)) %>% 
  select(-Order1, -Project)

ZP2 <- ZP1 %>% 
  # true grouping variables are smp_id, and GSL and life_stage2
  # but we wat to keep smp_date and smp_site
  group_by(Sample_ID,  Genus_sp_lifestage, Sample_date, Sample_site, Life_stage2) %>%
  #dups were generated by using mutate here, not summarize
  summarize(Zoop_biomass = sum(Zoop_biomass, na.rm=T)) %>% 
  ungroup() 


RotiferGroups <- c("Collothecaceae", "Ploima", "Flosculariaceae", "Rotifera spp.")
CopepodOther <- c("Poecilostomatoida", "Harpacticoida", "Arguloida")
ZP3 <- ZP2 %>% 
  left_join(Ztaxa, by = "Genus_sp_lifestage") %>% 
  # drop eggs
  filter(Life_stage2 != "Egg") %>% 
  droplevels() %>% 
  # combine rotifer orders 
  # drop "unusual" copepods
  mutate(MajorTaxaGroup = ifelse(Order1 %in% RotiferGroups, "Rotifers",
                                 ifelse(Order1 %in% CopepodOther, "CopepodOther", Order1))) %>%
  # pull out big predators
  mutate(MajorTaxaGroup2 = ifelse(Genus_sp_95toPresent == "Bythotrephes longimanus", "Bythotrephes longimanus",MajorTaxaGroup),
         MajorTaxaGroup2 = ifelse(Genus_sp_95toPresent == "Cercopagis pengoi", "Cercopagis pengoi",MajorTaxaGroup2),
         MajorTaxaGroup2 = ifelse(Genus_sp_95toPresent == "Leptodora kindti", "Leptodora kindti",
                                  ifelse(Genus_sp_95toPresent == "Leptodora kindti immature", "Leptodora kindti",MajorTaxaGroup2))) %>% 
  group_by(Sample_ID, Sample_date, Sample_site, MajorTaxaGroup2, Life_stage2) %>% 
  summarize(Zoop_biomass = sum(Zoop_biomass, na.rm = T)) %>% 
  mutate(MajorTaxaGroup3 = as.factor(paste0(MajorTaxaGroup2,"_",Life_stage2)))%>% 
  ungroup() %>% 
  select(-MajorTaxaGroup2, -Life_stage2) %>% 
  # remove "unusual" copepods, byth, and cercopagis
  # the byth and cercopagis data can not be trusted
  filter(!MajorTaxaGroup3 %in% c("CopepodOther_Nauplii", "CopepodOther_YO", "Cercopagis pengoi_YO", "Bythotrephes longimanus_YO")) %>% 
  droplevels()

ZP4 <- ZP3 %>% 
  pivot_wider(id_cols = c(Sample_ID, Sample_date, Sample_site, MajorTaxaGroup3), names_from = MajorTaxaGroup3, values_from = Zoop_biomass) %>% 
  left_join(Zsmp %>% 
              select(Sample_ID, Surface_temp), by = "Sample_ID") %>% 
  ungroup() %>% 
  rename(Calanoida = "Calanoida_YO", Cladocera = "Cladocera_YO", Cyclopoida = "Cyclopoida_YO", Leptodora= "Leptodora kindti_YO",
         Rotifers = "Rotifers_YO", Veligers = "Veneroida_Veliger", TempC = "Surface_temp") %>% 
  #20050922-27-918 has temp = 0
  mutate(TempC = ifelse(TempC <0.5, as.numeric("NA"), TempC))


############
# check data
############

# look are these closely - is anything weird, if so chase down
summary(ZP4)


# are there dups
dim(ZP4[duplicated(ZP4$Sample_ID) == TRUE,])

# ZP4c <- ZP4 %>% 
#   mutate(key = paste0(Sample_ID, "_", MajorTaxaGroup2),
#          dups = duplicated(key),
#          Sample_date = as.POSIXct(Sample_date, format = "%Y-%m-%d"))
# 
# # note
# ZP4c[ZP4c$dups == TRUE, ]


# summary by key
# not sure this is useful
# FTG2c %>% 
#   split(.$key) %>% 
#   map(summary)

# quick plot to check for weird data
ggplot(ZP4 %>% 
         pivot_longer(cols = c(Calanoida_Nauplii:TempC), names_to = "taxa", values_to = "biomass"), aes(y = log(biomass+1), x = Sample_date, color = Sample_site)) +
  geom_point() +
  facet_wrap(vars(taxa))

ggplot(ZP4, aes(y = TempC, x = Sample_date, color = Sample_site)) +
  geom_point()

ggplot(ZP4 %>% 
         mutate(doy = as.numeric(strftime(Sample_date, format = "%j")),
                Y = as.numeric(strftime(Sample_date, format = "%Y"))), aes(y = TempC, x = doy, color = Sample_site)) +
  geom_point() +
  facet_wrap(vars(Y))

ggplot(ZP4 %>% 
         mutate(doy = as.numeric(strftime(Sample_date, format = "%j")),
                Y = as.numeric(strftime(Sample_date, format = "%Y"))), aes(y = log(Cladocera+1), x = doy, color = Sample_site)) +
  geom_point() +
  facet_wrap(vars(Y))

ggplot(ZP4 %>% 
         mutate(doy = as.numeric(strftime(Sample_date, format = "%j")),
                Y = as.numeric(strftime(Sample_date, format = "%Y"))), aes(y = log(Calanoida+1), x = doy, color = Sample_site)) +
  geom_point() +
  facet_wrap(vars(Y))

ggplot(ZP4 %>% 
         pivot_longer(cols = c(Calanoida_Nauplii:Surface_temp), names_to = "taxa", values_to = "biomass") %>% 
        mutate(Y = strftime(Sample_date, format = "%Y"),
               # doy = as.numeric(strftime(Sample_date, format = "%j"))), aes(y = log(biomass+1), x = doy, color = Y)) +
  doy = as.numeric(strftime(Sample_date, format = "%j"))), aes(y = biomass, x = doy, color = Y)) +
  geom_point() +
  facet_wrap(vars(taxa), scales = "free_y")



# Write .csv file -- change filepath as needed.
write.csv(ZP4, file.path(here::here("03_exports","Amidon_LEPAS_WB_95_19.csv")))

save.image(file.path(here::here("04_SavedRimages","AmidonExport20210203_Rdat")))
