#####
# Code for pulling data for FTG
# Originally DRO (11 Feb 20), updated JMH 1 Feb 21

###
# Required libraries
###
library(tidyverse)
library(RSQLite)
library(here)

####
# Get data from database
####

# location of database
# database should be kept outside of repo
# I keep right outside of my github repo, find with getwd
# put in name of db
LEPASdbPath <- file.path(here::here("/Users/hood.211/Dropbox/JMH_dropbox/stephanson2/projects/6_Research/FADX09/01_LEPASgitHub/"), 
                        "LEPAS_20210201.db")

# Connect to database -- change filepath as needed.
lpdb <- dbConnect(SQLite(), LEPASdbPath)

# Pull relevant columns from tables using embedded SQL code.
zfin <- dbGetQuery(lpdb, "SELECT 
                   ZF.Sample_ID,
                   ZS.Sample_date,
                   ZS.Sample_site,
                   ZF.Genus_sp_lifestage,
                   ZF.Life_stage,
                   ZF.Number_counted,
                   ZF.Zoop_density,
                   ZF.Zoop_biomass,
                   ZF.Zoop_len_avg,
                   ZT.Order1,
                   ZT.FTG_Groups_1,  
                   ZT.biop_152_codes,
                   ZT.biop_152_names,
                   ZS.Project
                   FROM Zoop_final ZF
                   LEFT JOIN Zoop_sample_info ZS ON ZF.Sample_ID = ZS.Sample_ID
                   LEFT JOIN Zoop_taxa_groups ZT ON ZF.Genus_sp_lifestage = ZT.Genus_sp_lifestage
                   WHERE Sample_date LIKE '%2020%' AND Project='LEPAS'")


FTG1 <- zfin %>% 
  # turn NAs in density into zeros
  mutate(Zoop_density = ifelse(is.na(Zoop_density), 0, Zoop_density)) %>% 
  # make all younger individuals immatures - year-to-year comparions are not possible without this
  mutate(Genus_sp_lifestage = ifelse(Order1=="Calanoida" & Life_stage=="Younger", "Calanoida_immature", Genus_sp_lifestage),
         Genus_sp_lifestage = ifelse(Order1=="Cyclopoida" & Life_stage=="Younger", "Cyclopoida_immature", Genus_sp_lifestage)) %>% 
  mutate(across(c(Sample_ID, Sample_site,Life_stage, Project, Order1, Genus_sp_lifestage, FTG_Groups_1:biop_152_names), factor)) %>% 
  select(-Life_stage, -Project, -Order1) %>%
  # select FTG sites
  filter(Sample_site %in% c("1279_20m", "1281_10m", "27-918", "37-890")) %>% 
  # true grouping variables are smp_id, and GSL
  # but we want to keep FTG categories
  group_by(Sample_ID, Genus_sp_lifestage) %>%
  #dups were generated by using mutate here, not summarize
  summarize(Number_counted = sum(Number_counted, na.rm=T),
         Zoop_density = sum(Zoop_density, na.rm=T),
         Zoop_biomass = sum(Zoop_biomass, na.rm=T),
         Zoop_len_avg = mean(Zoop_len_avg, na.rm=T)) %>% 
  ungroup() 
  
  
  
  
# Write .csv file -- change filepath as needed.
write.csv(FTG1, "~/Desktop/FTG_LEPAS_Densities_2020_20210129.csv")



